config/routes.rb
Rails.application.routes.draw do

  root                          'home#index'
  get 'about'               =>  'home#about'
  get 'contact'             =>  'home#contact'
  get 'faq'                 =>  'home#faq'
  get 'policy'              =>  'home#policy'

  devise_for :users

resources :challenges do
  resources :comments
end

  resources :comments
  resources :groups
  resources :challenges
  resources :charges

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :challenge
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @challenge = Challenge.find(params[:challenge_id])
    @comment = @challenge.comments.create(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if @comment.user == current_user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else

      redirect_to challenges_path, notice: 'You dare not destroy this comment!'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :challenge_id, :comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.text_field :challenge_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('.comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<% @comments.each do |comment| %>
  <div class="comments">
    <div><%= comment.comment %></div>
    <div class="pull-right">
      <div><%= link_to 'Edit', edit_comment_path(comment) %> |
         <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @comment.challenge %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>