config/routes.rb
Rails.application.routes.draw do

  root                          'home#index'
  get 'about'               =>  'home#about'
  get 'contact'             =>  'home#contact'
  get 'faq'                 =>  'home#faq'
  get 'policy'              =>  'home#policy'

  devise_for :users

resources :challenges do
  resources :comments
end

  resources :comments
  resources :groups
  resources :challenges
  resources :charges

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

    belongs_to :creator, polymorphic: true

    has_many :accepts, as: :accepted
    has_many :user_acceptors, :through=> :accepts, :source => :acceptor, source_type: "User"
    has_many :group_acceptors, :through=> :accepts, :source => :acceptor, source_type: "Group"
    has_many :comments
    has_many :user_contributors, :through=> :contributions, :source => :contributor, source_type: "User"
    has_many :group_contributors, :through=> :contributions, :source => :contributor, source_type: "Group"
    has_many :contributions, as: :contributed

    has_and_belongs_to_many :categories

    validates :name,            presence: :true,
                                length: { maximum: 45 }
    validates :description,     presence: :true,
                                length: { within: 20..250 }

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @creator = current_user
    @challenge = @creator.challenges.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params) && @challenge.creator == @creator
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    if @challenge.creator == current_user
      @challenge.destroy
      respond_to do |format|
        format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    def set_user
      @creator = current_user
      if @creator.challenges.include?(@challenge)
        @challenge = @creator.challenges.find(@challenge.id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :description, :moderation_flag, :status, :terms, :creator_id, :creator_type, :requirement, :deadline, :payoff, :open_flag, :min_num, :max_num)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: 'A description of the Challenge' %>
  </div>
  <div class="field">
    <%= f.label :terms %><br>
    <%= f.text_area :terms %>
  </div>
  <div class="field">
    <%= f.label :requirement %><br>
    <%= f.text_area :requirement %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :payoff %><br>
    <%= f.number_field :payoff %>
  </div>
  <div class="field">
    <%= f.label :Is_the_challenge_open? %><br>
    <%= f.check_box :open_flag %>
  </div>
  <div class="field">
    <%= f.label :minimum_num_of_participants %><br>
    <%= f.number_field :min_num, in: 1..100 %>
  </div>
  <div class="field">
    <%= f.label :maximum_num_of_participants %><br>
    <%= f.number_field :max_num, in: 1..10000 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<% @page_title="Challenges" %>
<% @page_header="Challenges" %>

<div class="challenge-page">

  <div class="container challenge-list">

    <% @challenges.each do |challenge| %>

    <div class="container challenge-item">
      <h4 class="challenge-name"><%= challenge.name %></h4>
      <p class="challenge-info"><%= challenge.description %></p>
      <div class="container-fluid">
        <div class="row">
          <div data-toggle="collapse" data-target='#comment<%= challenge.id %>' class="col-sm-3 challenge-buttons">
            <%= link_to "View Comments", '#' %>
          </div>
          <div class="col-sm-3 challenge-buttons">
            <%= link_to 'Create A Challenge', new_challenge_path %>
          </div>

          <% if current_user == challenge.creator %>
          <div class="col-sm-3 challenge-buttons">
            <%= link_to 'Edit Challenge', edit_challenge_path(id: challenge.id) %>
          </div>
          <div class="col-sm-3 challenge-buttons">
            <%= link_to 'Delete Challenge', challenge, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          <% else %>
          <div class="col-sm-3 challenge-buttons">
            <%= link_to 'More Info', challenge %>
          </div>
          <div class="col-sm-3 challenge-buttons">
            <%= link_to 'contact', contact_path %>
          </div>
          <% end %>
        </div>
      </div>
      <div id='comment<%= challenge.id %>' class="collapse comments">

        <%= form_for([challenge, Comment.new], remote: true) do |f| %>
          <p><%= f.label :comment, "New Comment" %> <br>
            <%= f.text_area :comment %>
          </p>
          <p><%= f.submit "Add Comment"%> </p>
        <%end%>
        <%= render template: 'comments/index', object: @comments = challenge.comments.reverse %>
      </div>
    </div>

    <% end %>

  </div>

</div>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<% @page_header = "#{@challenge.name}" %>
<div class="challenge-main">

</div>

<% if current_user == @challenge.creator %>
  <%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<% end %>
<%= link_to 'Back', challenges_path %>