config/routes.rb
Rails.application.routes.draw do

  root                          'home#index'
  get 'about'               =>  'home#about'
  get 'contact'             =>  'home#contact'
  get 'faq'                 =>  'home#faq'
  get 'policy'              =>  'home#policy'

  devise_for :users

resources :challenges do
  resources :comments
end

  resources :comments
  resources :groups
  resources :challenges
  resources :charges

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default" role="navigation">
  <ul class="nav navbar-nav list">

    <li><%= link_to "About Us",         about_path %></li>
    <li><%= link_to "FAQ",              faq_path %></li>
    <li><%= link_to "Contact Us",       contact_path %></li>
    <li><%= link_to "Policy",           policy_path %></li>

  </ul>
</footer>

app/views/layouts/_header.html.erb
<% if !@page_header.blank? %>
  <div class="main_header text-center">
    <h1><%= @page_header %></h1>
    <% if !notice.blank? or !alert.blank? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top" role="navigation">

  <div class="row">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "YakYik", root_path, class: "navbar-brand" %>
      </div>
      <div class="container-fluid collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav list">

          <li><%= link_to "Challenges",       challenges_path %></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li><%= link_to destroy_user_session_path, method: :delete do%><span class="glyphicon glyphicon-log-out"></span> Logout<% end %></li>
          <% else%>
            <li><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-user"></span> Sign Up<% end %></li>
            <!-- Button trigger modal -->
            <li><a role="button" class="glyphicon glyphicon-log-in" data-toggle="modal" data-target="#myModal">  Login</a>
            </li>
            <li><a></a> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

</nav>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Log In</h3>
      </div>

      <div class="modal-body">
       <%= render template: 'devise/sessions/new'%>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_stripe_form.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? "Yakyik | #{@page_title} " : "Yakyik" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render '/layouts/shim' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="outer-wrapper">

    <%= render 'layouts/navbar' %>
    <% if @page_header %>
      <%= render 'layouts/header' %>
    <% end %>

    <div class="inner-wrapper">

      <%= yield %>

    </div>

    <%= render 'layouts/footer' %>

  </div>

</body>
</html>